drop package ut_xs_session_manager;
drop type ut_ras;
drop package ut_ras_utils;
drop type ut_ras_session_hash;
drop type ut_ras_session_info;
drop type ut_ns_attrib_list;
drop type ut_ns_attrib;
drop type ut_principal_list;
drop type ut_principal;
